# Number of training samples used by each client
training_samples: 600
# Number of test samples used by each client (validation)
test_samples: 100
# Parameters for local training
batch_size: 32
epochs: 10
